compiler:
    name: "gcc"
    limits:
        timeout: 30000
        cpu_quota: 25000
        cpu_period: 50000
        max_memory: "256M"
    command_line: "-Wall -O2 -std=c++11"

runner:
    name: "bin-network"
    limits:
        timeout: 1000
        cpu_quota: 25000
        cpu_period: 50000
        max_memory: "256M"
    server:
        image: "gcc:latest"
        file: "server"
    client:
        image: "gcc:latest"

evaluator:
    name: "json"
    tests:
        test1:
            store_output: "public"
